"""FedRAMP SSP evidence report generator for AgentGuard.

Queries the audit log, maps events to NIST 800-53 controls, and generates
a Markdown + JSON evidence package suitable for FedRAMP Moderate/High ATOs.
"""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from agentguard import __version__
from agentguard.audit_log import AuditLog
from agentguard.config import AgentGuardConfig
from agentguard.nist.controls_800_53 import CONTROLS, list_controls


class FedRAMPReporter:
    """Generates FedRAMP evidence artifacts from AgentGuard audit data."""

    def __init__(self, audit_log: AuditLog, config: AgentGuardConfig) -> None:
        """Initialize the reporter.

        Args:
            audit_log: The audit log to query.
            config: AgentGuard configuration (for agency/system metadata).
        """
        self.audit_log = audit_log
        self.config = config

    def _gather_stats(self) -> dict[str, Any]:
        """Compute summary statistics from the audit log."""
        events = self.audit_log.query(limit=10000)
        total = len(events)
        by_type: dict[str, int] = defaultdict(int)
        by_decision: dict[str, int] = defaultdict(int)
        by_control: dict[str, int] = defaultdict(int)

        for e in events:
            by_type[str(e.get("event_type", ""))] += 1
            by_decision[str(e.get("decision", ""))] += 1
            controls_raw = e.get("nist_controls_json", "[]") or "[]"
            try:
                controls = json.loads(controls_raw)
                for c in controls:
                    by_control[c] += 1
            except (json.JSONDecodeError, TypeError):
                pass

        valid, chain_msg = self.audit_log.verify_chain()

        return {
            "total_events": total,
            "by_event_type": dict(by_type),
            "by_decision": dict(by_decision),
            "by_control": dict(by_control),
            "chain_valid": valid,
            "chain_message": chain_msg,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    def generate_markdown(self, output_path: Path) -> None:
        """Generate a Markdown FedRAMP evidence document.

        Args:
            output_path: File path for the output Markdown file.
        """
        stats = self._gather_stats()
        cfg = self.config
        federal = cfg.federal

        lines: list[str] = [
            "# FedRAMP System Security Plan — Audit Evidence",
            "",
            f"**Generated by:** AgentGuard MCP v{__version__}",
            f"**Generated at:** {stats['generated_at']}",
            f"**Agency:** {federal.agency_id or 'Not configured'}",
            f"**System Name:** {federal.system_name or 'Not configured'}",
            f"**Impact Level:** {federal.impact_level}",
            f"**Operating Mode:** {cfg.mode}",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
            f"This document provides automated audit evidence generated by AgentGuard MCP "
            f"for FedRAMP {federal.impact_level} authorization. The evidence covers NIST 800-53 "
            f"Rev 5 controls implemented through AI agent tool call interception and policy enforcement.",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Total Audit Events | {stats['total_events']} |",
            f"| Hash Chain Integrity | {'PASS' if stats['chain_valid'] else 'FAIL'} |",
            f"| Signing Enabled | {'Yes' if cfg.signing_key else 'No'} |",
            "",
            "---",
            "",
            "## Audit Event Summary",
            "",
            "### Events by Type",
            "",
            "| Event Type | Count |",
            "|---|---|",
        ]

        for etype, count in sorted(stats["by_event_type"].items(), key=lambda x: -x[1]):
            lines.append(f"| {etype} | {count} |")

        lines += [
            "",
            "### Events by Decision",
            "",
            "| Decision | Count |",
            "|---|---|",
        ]
        for decision, count in sorted(stats["by_decision"].items(), key=lambda x: -x[1]):
            lines.append(f"| {decision} | {count} |")

        lines += [
            "",
            "---",
            "",
            "## NIST 800-53 Rev 5 Control Evidence",
            "",
            "The following controls are implemented by AgentGuard. Event counts reflect "
            "audit log entries tagged with each control during the reporting period.",
            "",
        ]

        for control in list_controls():
            cid = control.control_id
            event_count = stats["by_control"].get(cid, 0)
            lines += [
                f"### {cid} — {control.title}",
                "",
                f"**Family:** {control.family}",
                f"**Audit Events:** {event_count}",
                "",
                f"**Control Description:** {control.description}",
                "",
                f"**AgentGuard Implementation:** {control.agentguard_implementation}",
                "",
                f"**Code References:**",
            ]
            for ref in control.code_references:
                lines.append(f"- `{ref}`")
            lines.append("")

        lines += [
            "---",
            "",
            "## Audit Log Integrity",
            "",
            f"**Hash Chain Verification:** {'PASS' if stats['chain_valid'] else 'FAIL'}",
            f"**Result:** {stats['chain_message']}",
            "",
            "The AgentGuard audit log uses SHA-256 hash chaining. Each event includes "
            "the hash of the previous event, making any modification, deletion, or "
            "insertion detectable.",
            "",
            "In federal mode, each event is additionally signed with an Ed25519 private key. "
            "The public key can be provided to auditors for independent verification.",
            "",
            "---",
            "",
            "*This report was automatically generated. It should be reviewed by a qualified "
            "security professional before submission to a FedRAMP assessor.*",
        ]

        output_path.write_text("\n".join(lines))

    def generate_json(self, output_path: Path) -> None:
        """Generate a JSON FedRAMP evidence document.

        Args:
            output_path: File path for the output JSON file.
        """
        stats = self._gather_stats()
        cfg = self.config

        evidence = {
            "report_type": "fedramp_evidence",
            "agentguard_version": __version__,
            "generated_at": stats["generated_at"],
            "system": {
                "agency_id": cfg.federal.agency_id,
                "system_name": cfg.federal.system_name,
                "impact_level": cfg.federal.impact_level,
                "mode": cfg.mode,
            },
            "audit_summary": {
                "total_events": stats["total_events"],
                "chain_valid": stats["chain_valid"],
                "chain_message": stats["chain_message"],
                "by_event_type": stats["by_event_type"],
                "by_decision": stats["by_decision"],
                "by_control": stats["by_control"],
            },
            "controls": [
                {
                    "control_id": c.control_id,
                    "title": c.title,
                    "family": c.family,
                    "implementation": c.agentguard_implementation,
                    "audit_events": stats["by_control"].get(c.control_id, 0),
                }
                for c in list_controls()
            ],
        }

        output_path.write_text(json.dumps(evidence, indent=2))
