"""NIST AI RMF assessment report generator for AgentGuard."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from agentguard import __version__
from agentguard.audit_log import AuditLog
from agentguard.config import AgentGuardConfig
from agentguard.nist.ai_rmf import list_functions, list_by_function


class AIRMFReporter:
    """Generates NIST AI RMF assessment reports from AgentGuard audit data."""

    def __init__(self, audit_log: AuditLog, config: AgentGuardConfig) -> None:
        """Initialize the reporter."""
        self.audit_log = audit_log
        self.config = config

    def generate_markdown(self, output_path: Path) -> None:
        """Generate a Markdown NIST AI RMF assessment document."""
        now = datetime.now(timezone.utc).isoformat()
        cfg = self.config
        total_events = self.audit_log.count()
        valid, chain_msg = self.audit_log.verify_chain()

        lines: list[str] = [
            "# NIST AI Risk Management Framework — System Assessment",
            "",
            f"**Generated by:** AgentGuard MCP v{__version__}",
            f"**Generated at:** {now}",
            f"**System:** {cfg.federal.system_name or 'Not configured'}",
            f"**Operating Mode:** {cfg.mode}",
            "",
            "---",
            "",
            "## Assessment Summary",
            "",
            "This assessment maps AgentGuard MCP capabilities to the NIST AI RMF Core Functions "
            "(GOVERN, MAP, MEASURE, MANAGE). It is intended to support AI risk management programs "
            "in federal and regulated environments.",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Audit Events | {total_events} |",
            f"| Hash Chain | {'Verified' if valid else 'FAILED'} |",
            f"| Mode | {cfg.mode} |",
            "",
            "---",
            "",
        ]

        for function_name in ("GOVERN", "MAP", "MEASURE", "MANAGE"):
            lines += [
                f"## {function_name}",
                "",
            ]
            functions = list_by_function(function_name)
            for f in functions:
                lines += [
                    f"### {f.full_id} — {f.title}",
                    "",
                    f"**Description:** {f.description}",
                    "",
                    f"**AgentGuard Implementation:** {f.agentguard_implementation}",
                    "",
                    "**Code References:**",
                ]
                for ref in f.code_references:
                    lines.append(f"- `{ref}`")
                lines.append("")

        lines += [
            "---",
            "",
            "*This assessment was automatically generated. Review and validation by "
            "a qualified AI risk practitioner is required before formal submission.*",
        ]

        output_path.write_text("\n".join(lines))
