"""Plan of Action and Milestones (POA&M) generator for AgentGuard.

Queries the audit log for security violations (denied calls, detected threats)
and generates a POA&M document for federal compliance tracking.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from agentguard import __version__
from agentguard.audit_log import AuditLog
from agentguard.config import AgentGuardConfig


class POAMReporter:
    """Generates Plan of Action and Milestones reports from AgentGuard audit data."""

    FINDING_EVENT_TYPES = {
        "injection_detected": ("HIGH", "Prompt injection attempt detected", "SI-10"),
        "pii_detected": ("HIGH", "PII detected in tool call arguments", "SI-10"),
        "secret_detected": ("MEDIUM", "Secret or credential detected in tool call", "SC-8"),
        "tool_poisoning_detected": ("CRITICAL", "MCP tool description poisoning detected", "SI-4"),
        "tool_denied": ("LOW", "Tool call denied by policy", "AC-3"),
        "chain_violation": ("CRITICAL", "Audit log hash chain violation detected", "AU-9"),
    }

    def __init__(self, audit_log: AuditLog, config: AgentGuardConfig) -> None:
        """Initialize the POA&M reporter."""
        self.audit_log = audit_log
        self.config = config

    def _gather_findings(self) -> list[dict[str, Any]]:
        """Query the audit log for events that represent security findings."""
        findings: list[dict[str, Any]] = []
        finding_num = 1

        for event_type, (severity, description, control) in self.FINDING_EVENT_TYPES.items():
            events = self.audit_log.query(event_type=event_type, limit=1000)
            if events:
                findings.append({
                    "finding_id": f"AG-{finding_num:04d}",
                    "event_type": event_type,
                    "severity": severity,
                    "description": description,
                    "nist_control": control,
                    "occurrence_count": len(events),
                    "first_seen": events[-1].get("timestamp", ""),
                    "last_seen": events[0].get("timestamp", ""),
                    "status": "Open",
                    "remediation": self._get_remediation(event_type),
                })
                finding_num += 1

        return findings

    @staticmethod
    def _get_remediation(event_type: str) -> str:
        """Return suggested remediation for a finding type."""
        remediations = {
            "injection_detected": (
                "Review policy bundle to add explicit injection mitigation rules. "
                "Enable injection detector in federal mode. Investigate the source agent."
            ),
            "pii_detected": (
                "Enable PII scan with deny action in federal mode. "
                "Review which tool calls are transmitting PII and whether that is authorized."
            ),
            "secret_detected": (
                "Identify and rotate the leaked credential. "
                "Review the tool call that exposed it. Update developer workflows."
            ),
            "tool_poisoning_detected": (
                "Remove or replace the poisoned MCP server. "
                "Audit all tool descriptions served by the affected server."
            ),
            "tool_denied": (
                "Review policy allowlist to confirm the denied tool should remain blocked. "
                "If legitimate, add to allowlist with appropriate justification."
            ),
            "chain_violation": (
                "CRITICAL: Audit log integrity has been compromised. "
                "Preserve the current database as forensic evidence. "
                "Initiate incident response procedures."
            ),
        }
        return remediations.get(event_type, "Review and investigate. Update policy as needed.")

    def generate_markdown(self, output_path: Path) -> None:
        """Generate a Markdown POA&M document."""
        findings = self._gather_findings()
        now = datetime.now(timezone.utc).isoformat()
        cfg = self.config

        lines: list[str] = [
            "# Plan of Action and Milestones (POA&M)",
            "",
            f"**Generated by:** AgentGuard MCP v{__version__}",
            f"**Generated at:** {now}",
            f"**System:** {cfg.federal.system_name or 'Not configured'}",
            f"**Impact Level:** {cfg.federal.impact_level}",
            "",
            "---",
            "",
        ]

        if not findings:
            lines += [
                "## No Open Findings",
                "",
                "No security findings were detected in the audit log for the reporting period.",
            ]
        else:
            lines += [
                f"## Open Findings ({len(findings)} total)",
                "",
                "| Finding ID | Severity | Description | Control | Occurrences | Status |",
                "|---|---|---|---|---|---|",
            ]
            for f in findings:
                lines.append(
                    f"| {f['finding_id']} | {f['severity']} | {f['description']} "
                    f"| {f['nist_control']} | {f['occurrence_count']} | {f['status']} |"
                )

            lines += ["", "---", "", "## Finding Details", ""]
            for f in findings:
                lines += [
                    f"### {f['finding_id']} — {f['description']}",
                    "",
                    f"**Severity:** {f['severity']}",
                    f"**NIST Control:** {f['nist_control']}",
                    f"**Occurrences:** {f['occurrence_count']}",
                    f"**First Seen:** {f['first_seen']}",
                    f"**Last Seen:** {f['last_seen']}",
                    f"**Status:** {f['status']}",
                    "",
                    f"**Suggested Remediation:** {f['remediation']}",
                    "",
                ]

        output_path.write_text("\n".join(lines))
